const COLORS={red:{name:'Rot',hex:'#c7352d'},yellow:{name:'Gelb',hex:'#e3b51e'},green:{name:'Grün',hex:'#32934a'},blue:{name:'Blau',hex:'#2f6fd1'},purple:{name:'Lila',hex:'#7a45b8'},black:{name:'Schwarz',hex:'#272727'}};
const COLOR_ORDER=['red','yellow','green','blue','purple','black'];
const state={players:[],turn:0,die:null,phase:'lobby',room:null,host:false,me:null,rollAttempts:0,rolling:false};
let peer=null,hostConn=null,connections=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setConn(t){$('connection').textContent=t}
function makeId(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function initialPlayer(id,name,color){return {id,name,color,token:[-1,-1,-1,-1]}}
function createGameState(){return {players:state.players,turn:state.turn,die:null,phase:'playing',rollAttempts:0}}
function sendToAll(){if(!state.host)return;const msg={type:'state',state:{players:state.players,turn:state.turn,die:state.die,phase:state.phase,rollAttempts:state.rollAttempts}};connections.forEach(c=>{try{c.send(msg)}catch(e){}});render()}
function broadcast(msg){if(state.host)connections.forEach(c=>{try{c.send(msg)}catch(e){}})}
function setupPeerHost(){peer=new Peer(state.room,{debug:0});peer.on('open',()=>{setConn('Raum aktiv')});peer.on('connection',conn=>{connections.push(conn);conn.on('open',()=>{conn.send({type:'state',state:{players:state.players,turn:state.turn,die:state.die,phase:state.phase,rollAttempts:state.rollAttempts}})});conn.on('data',onMessage);conn.on('close',()=>{connections=connections.filter(x=>x!==conn);renderLobby()})});peer.on('error',e=>alert('Verbindung fehlgeschlagen: '+e.type))}
function setupPeerClient(code){peer=new Peer();peer.on('open',()=>{hostConn=peer.connect(code,{reliable:true});hostConn.on('open',()=>{setConn('Verbunden');hostConn.send({type:'join',name:state.me.name,color:state.me.color,id:state.me.id})});hostConn.on('data',onMessage);hostConn.on('close',()=>setConn('Getrennt'))});peer.on('error',e=>alert('Verbindung fehlgeschlagen. Prüfe den Raumcode.'))}
function onMessage(m){if(m.type==='join'&&state.host){if(state.players.length>=6)return;state.players.push(initialPlayer(m.id,m.name,m.color));sendToAll();renderLobby();return}if(m.type==='choose'&&state.host){const p=state.players.find(p=>p.id===m.id);if(p&&(!state.players.some(q=>q.color===m.color&&q.id!==p.id)))p.color=m.color;sendToAll();return}if(m.type==='start'&&state.host){startGame();return}if(m.type==='roll'&&state.host){roll(m.id);return}if(m.type==='move'&&state.host){move(m.token);return}if(m.type==='state'){Object.assign(state,m.state);render()}}
function availableColors(){return COLOR_ORDER.filter(c=>!state.players.some(p=>p.color===c))}
function selectColor(c){if(!availableColors().includes(c))return;state.me.color=c;const p=state.players.find(p=>p.id===state.me.id);if(p)p.color=c;if(state.host){sendToAll();renderLobby()}else if(hostConn)hostConn.send({type:'choose',id:state.me.id,color:c});renderLobby()}
function create(){const name=($('hostName').value.trim()||'Spieler 1').slice(0,18);state.host=true;state.room=makeId();state.me={id:'host-'+makeId(),name,color:null};state.players=[initialPlayer(state.me.id,name,null)];$('roomCode').textContent=state.room;$('colorPicker').classList.remove('hidden');$('waiting').classList.remove('hidden');setupPeerHost();renderLobby()}
function join(){const name=($('joinName').value.trim()||'Spieler').slice(0,18),code=$('joinCode').value.trim().toUpperCase();if(!code)return alert('Bitte Raumcode eingeben.');state.host=false;state.room=code;state.me={id:'p-'+makeId(),name,color:null};$('colorPicker').classList.remove('hidden');$('waiting').classList.add('hidden');setupPeerClient(code);renderLobby()}
function renderLobby(){const colors=$('colors');if(!colors)return;colors.innerHTML=COLOR_ORDER.map(c=>`<button class="color-btn color-${c} ${state.me&&state.me.color===c?'selected':''} ${!availableColors().includes(c)&&(!state.me||state.me.color!==c)?'taken':''}" data-c="${c}" ${!availableColors().includes(c)&&(!state.me||state.me.color!==c)?'disabled':''}>${COLORS[c].name}</button>`).join('');colors.querySelectorAll('button').forEach(b=>b.onclick=()=>selectColor(b.dataset.c));$('pickHint').textContent=state.me?.color?'Gewählt: '+COLORS[state.me.color].name:'Wähle eine freie Farbe.';const list=$('playersList');if(list)list.innerHTML=state.players.map(p=>`<div class="player-row"><span class="dot" style="background:${p.color?COLORS[p.color].hex:'#777'}"></span><strong>${esc(p.name)}</strong><span>${p.color?COLORS[p.color].name:'Farbe wählen'}</span></div>`).join('');if(state.host)$('startBtn').disabled=state.players.length<2||state.players.some(p=>!p.color);else $('startBtn').style.display='none'}
function startGame(){if(!state.host)return; if(state.players.length<2||state.players.some(p=>!p.color))return alert('Mindestens 2 Spieler und alle müssen eine Farbe wählen.');state.turn=Math.floor(Math.random()*state.players.length);state.phase='playing';state.die=null;state.rollAttempts=0;connections.forEach(c=>{try{c.send({type:'state',state:createGameState()})}catch(e){}});render()}
// 48-field classic six-player ring: 8 white track spaces per color sector.
const track=[];for(let i=0;i<48;i++){const a=2*Math.PI*i/48-Math.PI/2;track.push({x:50+43*Math.cos(a),y:50+43*Math.sin(a)})}
const starts=COLOR_ORDER.map((c,i)=>i*8); // A field for each colour
const homes=[{x:8,y:8},{x:74,y:8},{x:74,y:74},{x:8,y:74},{x:38,y:2},{x:38,y:80}];
function buildBoard(){const b=$('board');b.innerHTML='';track.forEach((p,i)=>{const el=document.createElement('div');el.className='cell track';el.dataset.pos=i;el.style.left=(p.x-2.15)+'%';el.style.top=(p.y-2.15)+'%';const ci=COLOR_ORDER.findIndex((c,j)=>starts[j]===i);if(ci>=0){el.classList.add('a');el.style.setProperty('--c',COLORS[COLOR_ORDER[ci]].hex);el.textContent='A';}el.onclick=()=>{if(state.host&&state.die)chooseMove(i)};b.appendChild(el)});COLOR_ORDER.forEach((c,i)=>{const h=document.createElement('div');h.className='home';h.style.left=homes[i].x+'%';h.style.top=homes[i].y+'%';h.style.setProperty('--c',COLORS[c].hex);h.innerHTML=`<span class="home-title">${COLORS[c].name} · B</span>`;for(let k=0;k<4;k++){const s=document.createElement('div');s.className='base';s.dataset.home=`${c}-${k}`;h.appendChild(s)}b.appendChild(h)});const center=document.createElement('div');center.style.cssText='position:absolute;left:34%;top:34%;width:32%;height:32%;border:3px solid #7e6b4f;background:#eadfc9;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);';center.innerHTML='<div style="display:grid;place-items:center;height:100%;font:900 18px Georgia;color:#6c5b43">MÄDN</div>';b.appendChild(center)}
function renderBoard(){document.querySelectorAll('.token').forEach(x=>x.remove());state.players.forEach((p,pi)=>{p.token.forEach((pos,ti)=>{const t=document.createElement('div');t.className='token';t.style.setProperty('--c',COLORS[p.color].hex);t.title=p.name;if(pos<0){const base=document.querySelector(`[data-home="${p.color}-${ti}"]`);if(base)base.appendChild(t)}else if(pos>=100){const goalIndex=pos-100;const h=homes[COLOR_ORDER.indexOf(p.color)];t.classList.add('onboard');t.style.position='absolute';t.style.left=(h.x+4+goalIndex*3.2)+'%';t.style.top=(h.y+7)+'%';$('board').appendChild(t)}else{const pt=track[pos];t.style.position='absolute';t.style.left=(pt.x-1.55)+'%';t.style.top=(pt.y-1.55)+'%';if(p.id===state.me?.id&&state.die!==null&&canMove(p,ti,state.die))t.classList.add('movable');t.onclick=()=>{if(state.host&&p.id===state.me.id&&state.die!==null)move(ti);else if(!state.host&&p.id===state.me.id&&state.die!==null)hostConn?.send({type:'move',token:ti})};$('board').appendChild(t)}})})}
function canMove(p,ti,n){const pos=p.token[ti];if(pos<0)return n===6;const next=pos+n;if(next<48)return !state.players.some(q=>q.id!==p.id&&q.token.includes(next))||true;const goal=next-48;if(goal>=0&&goal<4)return !p.token.some((x,j)=>j!==ti&&x===100+goal);return false}
function legalTokens(p,n){return p.token.map((_,i)=>canMove(p,i,n)?i:null).filter(x=>x!==null)}
function roll(requesterId=state.me.id){if(!state.host||state.phase!=='playing'||state.rolling)return;const p=state.players[state.turn];if(!p)return;if(requesterId!==p.id)returnstate.rolling=true;const n=Math.floor(Math.random()*6)+1;state.die=n;state.rollAttempts++;render();setTimeout(()=>{state.rolling=false;const legal=legalTokens(p,n);if(legal.length===0){if(n===6){state.die=null;state.rollAttempts=0;nextTurn()}else if(p.token.every(x=>x<0)){if(state.rollAttempts<3){state.die=null;render()}else{state.die=null;state.rollAttempts=0;nextTurn()}}else{state.die=null;state.rollAttempts=0;nextTurn()}}else if(n===6&&p.token.every(x=>x<0)){move(legal[0]);}else if(legal.length===1){move(legal[0]);}else{render();}sendToAll()},500)}
function chooseMove(pos){const p=state.players[state.turn],ti= p.token.findIndex(x=>x===pos);if(ti>=0)move(ti)}
function move(ti){if(!state.host||state.die===null)return;const p=state.players[state.turn],n=state.die;if(!legalTokens(p,n).includes(ti))return;let next=p.token[ti];if(next<0)next=starts[COLOR_ORDER.indexOf(p.color)];else next+=n;if(next>=48)next=100+(next-48);if(next<100){state.players.forEach(q=>{if(q.id!==p.id){q.token=q.token.map(x=>x===next?-1:x)}})}p.token[ti]=next;const won=p.token.every(x=>x>=100);const again=n===6&&!won;if(won){state.phase='finished'}if(again){state.die=null;state.rollAttempts=0}else{state.die=null;state.rollAttempts=0;nextTurn()}sendToAll();render()}
function nextTurn(){state.turn=(state.turn+1)%state.players.length;state.die=null;state.rollAttempts=0}
function render(){if(state.phase==='lobby'){renderLobby();return}$('lobby').classList.add('hidden');$('game').classList.remove('hidden');buildBoard();$('scoreboard').innerHTML=state.players.map((p,i)=>`<div class="player-row ${i===state.turn?'active':''}"><span class="dot" style="background:${COLORS[p.color].hex}"></span><strong>${esc(p.name)}</strong><span>${p.token.filter(x=>x>=100).length}/4</span></div>`).join('');const p=state.players[state.turn];$('turnName').textContent=p?.name||'–';$('turnColor').textContent=p?COLORS[p.color].name:'–';$('turnColor').style.color=p?COLORS[p.color].hex:'';$('die').textContent=state.die||'–';const mine=p&&p.id===state.me?.id;$('rollBtn').disabled=!state.host||!mine||state.die!==null||state.phase!=='playing';$('status').textContent=state.phase==='finished'?`${p.name} hat alle vier Figuren im Ziel.`:(mine?(state.die===null?'Du bist dran – würfle.': 'Wähle eine blinkende Figur.'):`${p?.name||''} ist am Zug.`);renderBoard()}
$('createBtn').onclick=create;$('joinBtn').onclick=join;$('startBtn').onclick=()=>{if(state.host)startGame();else hostConn?.send({type:'start'})};$('rollBtn').onclick=()=>{if(state.host)roll(state.me.id);else hostConn?.send({type:'roll',id:state.me.id})};$('newGameBtn').onclick=()=>location.reload();renderLobby();
