const COLORS={red:{name:'Rot',hex:'#c7352d'},yellow:{name:'Gelb',hex:'#e3b51e'},green:{name:'Grün',hex:'#32934a'},blue:{name:'Blau',hex:'#2f6fd1'},purple:{name:'Lila',hex:'#7a45b8'},black:{name:'Schwarz',hex:'#272727'}};
const COLOR_ORDER=['red','yellow','green','blue','purple','black'];
const state={players:[],turn:0,die:null,phase:'lobby',room:null,host:false,me:null,rollAttempts:0};
let peer=null,hostConn=null,connections=[]; let joinTimer=null;
const $=id=>document.getElementById(id); const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setConn(t){$('connection').textContent=t}
function error(t){$('errorBox').textContent=t;$('errorBox').classList.remove('hidden')}
function clearError(){$('errorBox').classList.add('hidden')}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
function makeId(prefix){return prefix+'-'+crypto.randomUUID().replaceAll('-','').slice(0,20)}
function initialPlayer(id,name,color){return{id,name,color,token:[-1,-1,-1,-1]}}
function snapshot(){return{players:state.players,turn:state.turn,die:state.die,phase:state.phase,rollAttempts:state.rollAttempts,room:state.room}}
function sendState(c){try{if(c&&c.open)c.send({type:'state',state:snapshot()})}catch(e){}}
function sendToAll(){if(!state.host)return;connections.forEach(sendState);render()}
function availableColors(){return COLOR_ORDER.filter(c=>!state.players.some(p=>p.color===c))}
function bindConnection(conn){connections.push(conn);conn.on('open',()=>{sendState(conn);setConn('Raum aktiv')});conn.on('data',onMessage);conn.on('close',()=>{connections=connections.filter(x=>x!==conn);renderLobby()});conn.on('error',()=>{connections=connections.filter(x=>x!==conn);renderLobby()})}
function setupHost(){const peerId='maedn-'+state.room.toLowerCase();peer=new Peer(peerId,{debug:1});peer.on('open',()=>{setConn('Raum aktiv');renderLobby()});peer.on('connection',bindConnection);peer.on('error',e=>{console.error(e);if(e.type==='unavailable-id'){error('Dieser Raumcode ist gerade belegt. Bitte neuen Raum erstellen.');setConn('Fehler')}else error('Verbindungsfehler: '+e.type)});}
function setupClient(code){peer=new Peer(undefined,{debug:1});peer.on('open',()=>connectToHost(code));peer.on('error',e=>{console.error(e);if(e.type==='peer-unavailable')error('Raum nicht gefunden. Bitte den Raumcode exakt prüfen und sicherstellen, dass der Gastgeber die Seite noch geöffnet hat.');else error('Verbindungsfehler: '+e.type);setConn('Nicht verbunden')});}
function connectToHost(code){clearError();setConn('Verbinde…');const hostId='maedn-'+code.toLowerCase();hostConn=peer.connect(hostId,{reliable:true,serialization:'json'});let opened=false;hostConn.on('open',()=>{opened=true;clearTimeout(joinTimer);setConn('Verbunden');hostConn.send({type:'join',id:state.me.id,name:state.me.name,color:state.me.color})});hostConn.on('data',onMessage);hostConn.on('close',()=>{setConn('Getrennt');error('Die Verbindung zum Raum wurde beendet.')});hostConn.on('error',e=>{console.error(e);error('Beitritt fehlgeschlagen. Prüfe den Raumcode.');setConn('Fehler')});joinTimer=setTimeout(()=>{if(!opened){error('Der Raum antwortet nicht. Prüfe den Code oder ob der Gastgeber den Raum noch geöffnet hat.');setConn('Keine Antwort')}},8000)}
function onMessage(m){if(!m||!m.type)return;
 if(m.type==='join'&&state.host){if(state.players.length>=6)return; if(state.players.some(p=>p.id===m.id))return; if(state.players.some(p=>p.color&&p.color===m.color))m.color=null;state.players.push(initialPlayer(m.id,m.name,m.color));sendToAll();renderLobby();return}
 if(m.type==='choose'&&state.host){const p=state.players.find(p=>p.id===m.id);if(p&&(!state.players.some(q=>q.id!==p.id&&q.color===m.color)))p.color=m.color;sendToAll();return}
 if(m.type==='start'&&state.host){startGame();return}
 if(m.type==='roll'&&state.host){if(m.id===state.players[state.turn]?.id)roll(m.id);return}
 if(m.type==='move'&&state.host){if(m.id===state.players[state.turn]?.id)move(m.token);return}
 if(m.type==='state'){const me=state.me;Object.assign(state,m.state);state.me=me;render();return}}
function selectColor(c){if(!state.me||(!availableColors().includes(c)&&state.me.color!==c))return;state.me.color=c;const p=state.players.find(p=>p.id===state.me.id);if(p)p.color=c;if(state.host){sendToAll()}else if(hostConn?.open)hostConn.send({type:'choose',id:state.me.id,color:c});renderLobby()}
function create(){clearError();const name=($('hostName').value.trim()||'Spieler 1').slice(0,18);state.host=true;state.room=makeCode();state.me={id:makeId('host'),name,color:null};state.players=[initialPlayer(state.me.id,name,null)];$('hostRoom').classList.remove('hidden');$('roomCode').textContent=state.room;$('colorPicker').classList.remove('hidden');$('waiting').classList.remove('hidden');$('createBtn').disabled=true;setupHost();renderLobby();render()}
function join(){clearError();const name=($('joinName').value.trim()||'Spieler').slice(0,18),code=$('joinCode').value.trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{6}$/.test(code))return error('Bitte einen gültigen 6-stelligen Raumcode eingeben.');state.host=false;state.room=code;state.me={id:makeId('player'),name,color:null};$('colorPicker').classList.remove('hidden');$('waiting').classList.remove('hidden');$('startBtn').classList.add('hidden');$('joinBtn').disabled=true;setupClient(code);renderLobby();render()}
function renderLobby(){const colors=$('colors');colors.innerHTML=COLOR_ORDER.map(c=>{const free=availableColors().includes(c)||state.me?.color===c;return`<button type="button" class="color-btn color-${c} ${state.me?.color===c?'selected':''}" ${free?'':'disabled'} data-c="${c}">${COLORS[c].name}</button>`}).join('');colors.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>selectColor(b.dataset.c)));$('pickHint').textContent=state.me?.color?'Gewählt: '+COLORS[state.me.color].name:'Bitte eine freie Farbe wählen.';const list=$('playersList');list.innerHTML=state.players.map(p=>`<div class="player-row"><span class="dot" style="background:${p.color?COLORS[p.color].hex:'#999'}"></span><strong>${esc(p.name)}</strong><span>${p.color?COLORS[p.color].name:'wählt…'}</span></div>`).join('');if(state.host){$('waitStatus').textContent=state.players.length<2?'Warte auf mindestens einen weiteren Spieler.':state.players.some(p=>!p.color)?'Alle Spieler müssen zuerst eine Farbe wählen.':'Alle bereit.';$('startBtn').classList.remove('hidden');$('startBtn').disabled=state.players.length<2||state.players.some(p=>!p.color)}else $('waitStatus').textContent=state.players.length?'Mit Raum verbunden. Warte auf den Gastgeber.':'Verbinde mit Raum…'}
function startGame(){if(!state.host||state.players.length<2||state.players.some(p=>!p.color))return;state.turn=Math.floor(Math.random()*state.players.length);state.phase='playing';state.die=null;state.rollAttempts=0;sendToAll();render()}
const track=[];for(let i=0;i<48;i++){const a=2*Math.PI*i/48-Math.PI/2;track.push({x:50+43*Math.cos(a),y:50+43*Math.sin(a)})}const starts=COLOR_ORDER.map((c,i)=>i*8);const homes=[{x:5,y:5},{x:71,y:5},{x:71,y:71},{x:5,y:71},{x:38,y:3},{x:38,y:73}];
function buildBoard(){const b=$('board');b.innerHTML='';track.forEach((p,i)=>{const el=document.createElement('div');el.className='cell track';el.style.left=(p.x-2.15)+'%';el.style.top=(p.y-2.15)+'%';const ci=starts.indexOf(i);if(ci>=0){el.classList.add('a');el.style.setProperty('--c',COLORS[COLOR_ORDER[ci]].hex);el.textContent='A'}b.appendChild(el)});COLOR_ORDER.forEach((c,i)=>{const h=document.createElement('div');h.className='home';h.style.left=homes[i].x+'%';h.style.top=homes[i].y+'%';h.style.setProperty('--c',COLORS[c].hex);h.innerHTML='<span class="home-title">'+COLORS[c].name+' · B</span>';for(let k=0;k<4;k++){const s=document.createElement('div');s.className='base';s.dataset.home=`${c}-${k}`;h.appendChild(s)}b.appendChild(h)});const center=document.createElement('div');center.style.cssText='position:absolute;left:34%;top:34%;width:32%;height:32%;border:3px solid #7e6b4f;background:#eadfc9;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);display:grid;place-items:center;font:900 18px Georgia;color:#6c5b43';center.textContent='MÄDN';b.appendChild(center)}
function canMove(p,ti,n){const pos=p.token[ti];if(pos<0)return n===6;let next=pos+n;if(next<48)return true;const goal=next-48;return goal>=0&&goal<4&&!p.token.some((x,j)=>j!==ti&&x===100+goal)}
function legalTokens(p,n){return p.token.map((_,i)=>canMove(p,i,n)?i:null).filter(x=>x!==null)}
function renderBoard(){document.querySelectorAll('.token').forEach(x=>x.remove());state.players.forEach(p=>p.token.forEach((pos,ti)=>{const t=document.createElement('div');t.className='token';t.style.setProperty('--c',COLORS[p.color].hex);if(pos<0){const base=document.querySelector(`[data-home="${p.color}-${ti}"]`);if(base)base.appendChild(t)}else if(pos>=100){const h=homes[COLOR_ORDER.indexOf(p.color)];t.style.position='absolute';t.style.left=(h.x+6+(pos-100)*4)+'%';t.style.top=(h.y+9)+'%';$('board').appendChild(t)}else{const pt=track[pos];t.style.position='absolute';t.style.left=(pt.x-1.55)+'%';t.style.top=(pt.y-1.55)+'%';if(p.id===state.me?.id&&state.die!==null&&canMove(p,ti,state.die)){t.classList.add('movable');t.addEventListener('click',()=>state.host?move(ti):hostConn?.send({type:'move',id:state.me.id,token:ti}))}$('board').appendChild(t)}}))}
function nextTurn(){state.turn=(state.turn+1)%state.players.length;state.die=null;state.rollAttempts=0}
function roll(id){if(!state.host||state.phase!=='playing'||state.die!==null)return;const p=state.players[state.turn];if(!p||p.id!==id)return;const n=Math.floor(Math.random()*6)+1;state.die=n;state.rollAttempts++;render();setTimeout(()=>{const legal=legalTokens(p,n);if(!legal.length){if(n!==6&&p.token.every(x=>x<0)&&state.rollAttempts<3){state.die=null}else{state.die=null;state.rollAttempts=0;nextTurn()}}else if(n===6&&p.token.every(x=>x<0)){move(legal[0]);return}else if(legal.length===1){move(legal[0]);return}sendToAll();render()},450)}
function move(ti){if(!state.host||state.die===null)return;const p=state.players[state.turn],n=state.die;if(!p||!legalTokens(p,n).includes(ti))return;let next=p.token[ti];if(next<0)next=starts[COLOR_ORDER.indexOf(p.color)];else next+=n;if(next>=48)next=100+(next-48);if(next<100)state.players.forEach(q=>{if(q.id!==p.id)q.token=q.token.map(x=>x===next?-1:x)});p.token[ti]=next;const won=p.token.every(x=>x>=100);if(won)state.phase='finished';const again=n===6&&!won;state.die=null;state.rollAttempts=0;if(!again)nextTurn();sendToAll();render()}
function render(){if(state.phase==='lobby'){renderLobby();$('game').classList.remove('hidden');buildBoard();$('scoreboard').innerHTML=state.players.length?state.players.map(p=>`<div class="player-row"><span class="dot" style="background:${p.color?COLORS[p.color].hex:'#999'}"></span><strong>${esc(p.name)}</strong><span>${p.color?COLORS[p.color].name:'wählt…'}</span></div>`).join(''):'<p class="muted">Noch keine Spieler verbunden.</p>';$('turnName').textContent='Warte auf Start';$('turnColor').textContent=state.players.length+' Spieler im Raum';$('turnColor').style.color='';$('die').textContent='–';$('rollBtn').disabled=true;$('status').textContent=state.host?(state.players.length<2?'Warte auf weitere Spieler.':'Spiel kann gestartet werden.'):'Warte auf den Gastgeber.';renderBoard();return}$('lobby').classList.add('hidden');$('game').classList.remove('hidden');buildBoard();$('scoreboard').innerHTML=state.players.map((p,i)=>`<div class="player-row ${i===state.turn?'active':''}"><span class="dot" style="background:${COLORS[p.color].hex}"></span><strong>${esc(p.name)}</strong><span>${p.token.filter(x=>x>=100).length}/4</span></div>`).join('');const p=state.players[state.turn];$('turnName').textContent=p?.name||'–';$('turnColor').textContent=p?COLORS[p.color].name:'–';$('turnColor').style.color=p?COLORS[p.color].hex:'';$('die').textContent=state.die||'–';const mine=p&&p.id===state.me?.id;$('rollBtn').disabled=!mine||state.die!==null||state.phase!=='playing';$('status').textContent=state.phase==='finished'?`${p.name} hat gewonnen.`:(mine?(state.die===null?'Du bist dran – würfle.':'Wähle eine blinkende Figur.'):`${p?.name||''} ist am Zug.`);renderBoard()}
$('createBtn').addEventListener('click',create);$('joinBtn').addEventListener('click',join);$('startBtn').addEventListener('click',()=>state.host&&startGame());$('rollBtn').addEventListener('click',()=>state.host?roll(state.me.id):hostConn?.send({type:'roll',id:state.me.id}));$('newGameBtn').addEventListener('click',()=>location.reload());renderLobby();