const COLORS={red:{name:'Rot',hex:'#c7352d'},yellow:{name:'Gelb',hex:'#d5aa13'},green:{name:'Grün',hex:'#2f8c45'},blue:{name:'Blau',hex:'#2f6fd1'},purple:{name:'Lila',hex:'#7643ad'},black:{name:'Schwarz',hex:'#292929'}};
// Positionen entsprechen der klassischen 6-Personen-Anordnung: Rot oben, Grün oben rechts,
// Lila unten rechts, Gelb unten, Schwarz unten links, Blau oben links.
const ORDER=['red','green','purple','yellow','black','blue'];
const state={players:[],turn:0,die:null,phase:'lobby',room:null,host:false,me:null,rollAttempts:0};
let peer=null,hostConn=null,connections=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setConn(t){$('connection').textContent=t}
function error(t){$('errorBox').textContent=t;$('errorBox').classList.remove('hidden')}
function clearError(){$('errorBox').classList.add('hidden')}
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function id(){return crypto.randomUUID().replaceAll('-','').slice(0,18)}
function player(id,name,color){return{id,name,color,token:[-1,-1,-1,-1]}}
function snapshot(){return JSON.parse(JSON.stringify({players:state.players,turn:state.turn,die:state.die,phase:state.phase,rollAttempts:state.rollAttempts,room:state.room}))}
function send(c,msg){try{if(c?.open)c.send(msg)}catch(e){console.warn(e)}}
function broadcast(){if(!state.host)return;const msg={type:'state',state:snapshot()};connections.forEach(c=>send(c,msg));render()}
function freeColors(){return ORDER.filter(c=>!state.players.some(p=>p.color===c))}
function bind(conn){connections.push(conn);conn.on('open',()=>{send(conn,{type:'state',state:snapshot()});setConn('Raum aktiv');renderLobby()});conn.on('data',onMessage);conn.on('close',()=>{connections=connections.filter(c=>c!==conn);renderLobby()});conn.on('error',e=>{console.warn('connection',e);connections=connections.filter(c=>c!==conn);renderLobby()})}
function setupHost(){peer=new Peer('maedn-'+state.room.toLowerCase(),{debug:0});peer.on('open',()=>{setConn('Raum aktiv');renderLobby()});peer.on('connection',bind);peer.on('error',e=>{console.error(e);error(e.type==='unavailable-id'?'Raumcode bereits vergeben. Bitte neuen Raum erstellen.':'Verbindungsfehler: '+e.type);setConn('Fehler')})}
function setupClient(c){peer=new Peer(undefined,{debug:0});peer.on('open',()=>{hostConn=peer.connect('maedn-'+c.toLowerCase(),{reliable:true});hostConn.on('open',()=>{clearError();setConn('Verbunden');send(hostConn,{type:'join',id:state.me.id,name:state.me.name,color:state.me.color})});hostConn.on('data',onMessage);hostConn.on('close',()=>{setConn('Getrennt');error('Die Verbindung zum Gastgeber wurde beendet.')});hostConn.on('error',e=>{console.warn(e);setConn('Fehler');error('Beitritt fehlgeschlagen. Prüfe den Raumcode.')})});peer.on('error',e=>{console.error(e);setConn('Fehler');error(e.type==='peer-unavailable'?'Raum nicht gefunden. Prüfe den Raumcode und ob der Gastgeber den Raum geöffnet hat.':'Verbindungsfehler: '+e.type)})}
function onMessage(m){if(!m?.type)return;
 if(m.type==='join'&&state.host){if(state.phase!=='lobby'||state.players.length>=6)return;if(state.players.some(p=>p.id===m.id))return;const color=freeColors().includes(m.color)?m.color:null;state.players.push(player(m.id,String(m.name||'Spieler').slice(0,18),color));broadcast();return}
 if(m.type==='choose'&&state.host){if(state.phase!=='lobby')return;const p=state.players.find(p=>p.id===m.id);if(!p)return;if(!freeColors().includes(m.color)&&p.color!==m.color)return;p.color=m.color;broadcast();return}
 if(m.type==='start'&&state.host){startGame();return}
 if(m.type==='roll'&&state.host){if(m.id===state.players[state.turn]?.id)roll();return}
 if(m.type==='move'&&state.host){if(m.id===state.players[state.turn]?.id)move(m.token);return}
 if(m.type==='state'){const me=state.me;const host=state.host;Object.assign(state,m.state);state.me=me;state.host=host;render()}}
function selectColor(c){if(!state.me)return;if(!freeColors().includes(c)&&state.me.color!==c)return;state.me.color=c;const p=state.players.find(p=>p.id===state.me.id);if(p)p.color=c;if(state.host)broadcast();else send(hostConn,{type:'choose',id:state.me.id,color:c});renderLobby()}
function create(){clearError();const name=($('hostName').value.trim()||'Spieler 1').slice(0,18);state.host=true;state.room=code();state.me={id:'host-'+id(),name,color:null};state.players=[player(state.me.id,name,null)];$('hostRoom').classList.remove('hidden');$('roomCode').textContent=state.room;$('colorPicker').classList.remove('hidden');$('waiting').classList.remove('hidden');$('createBtn').disabled=true;setupHost();renderLobby();showGame()}
function join(){clearError();const name=($('joinName').value.trim()||'Spieler').slice(0,18),c=$('joinCode').value.trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{6}$/.test(c))return error('Bitte einen gültigen 6-stelligen Raumcode eingeben.');state.host=false;state.room=c;state.me={id:'p-'+id(),name,color:null};$('colorPicker').classList.remove('hidden');$('waiting').classList.remove('hidden');$('joinBtn').disabled=true;setupClient(c);renderLobby();showGame()}
function renderLobby(){const colors=$('colors');colors.innerHTML=ORDER.map(c=>{const ok=freeColors().includes(c)||state.me?.color===c;return`<button type="button" class="color-btn color-${c} ${state.me?.color===c?'selected':''}" ${ok?'':'disabled'} data-c="${c}">${COLORS[c].name}</button>`}).join('');colors.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>selectColor(b.dataset.c)));$('pickHint').textContent=state.me?.color?'Gewählt: '+COLORS[state.me.color].name:'Bitte eine freie Farbe wählen.';$('playersList').innerHTML=state.players.map(p=>`<div class="player-row"><span class="dot" style="background:${p.color?COLORS[p.color].hex:'#999'}"></span><strong>${esc(p.name)}</strong><span>${p.color?COLORS[p.color].name:'wählt…'}</span></div>`).join('');if(state.host){$('waitStatus').textContent=state.players.length<2?'Warte auf weitere Spieler.':state.players.some(p=>!p.color)?'Alle Spieler müssen eine Farbe wählen.':'Mindestens 2 Spieler bereit.';$('startBtn').classList.remove('hidden');$('startBtn').disabled=state.players.length<2||state.players.some(p=>!p.color)}else{$('waitStatus').textContent='Mit Raum verbunden. Warte auf den Gastgeber.';$('startBtn').classList.add('hidden')}}
function showGame(){$('game').classList.remove('hidden');buildBoard();render()}
function startGame(){if(!state.host||state.players.length<2||state.players.some(p=>!p.color))return;state.turn=Math.floor(Math.random()*state.players.length);state.phase='playing';state.die=null;state.rollAttempts=0;broadcast();render()}
// 48-Felder-Laufbahn: sechs identische 8-Felder-Sektoren. Das ist die kleine klassische 6-Personen-Variante.
const track=[];const homeCenters=[];const goals=[];
for(let s=0;s<6;s++){const base=-Math.PI/2+s*Math.PI/3;homeCenters.push({x:50+43*Math.cos(base),y:50+43*Math.sin(base)});goals.push([24,20,16,12].map(r=>({x:50+r*Math.cos(base),y:50+r*Math.sin(base)})));for(let k=0;k<8;k++){const t=k/8;const a=base+t*Math.PI/3;const r=k===0?43:(k===7?34.5:(39+((k%2)*1.8)));track.push({x:50+r*Math.cos(a),y:50+r*Math.sin(a)})}}
const starts=ORDER.map((_,i)=>i*8);
function buildBoard(){const b=$('board');b.innerHTML='';track.forEach((p,i)=>{const e=document.createElement('div');e.className='cell'+(starts.includes(i)?' a':'');e.style.left=(p.x-2.6)+'%';e.style.top=(p.y-2.6)+'%';if(starts.includes(i)){const c=ORDER[starts.indexOf(i)];e.style.setProperty('--c',COLORS[c].hex);e.textContent='A'}b.appendChild(e)});ORDER.forEach((c,i)=>{const h=document.createElement('div');h.className='home';h.style.left=(homeCenters[i].x-9)+'%';h.style.top=(homeCenters[i].y-9)+'%';h.style.setProperty('--c',COLORS[c].hex);h.innerHTML='<span class="home-title">B</span>';for(let k=0;k<4;k++){const s=document.createElement('div');s.className='base';s.dataset.home=`${c}-${k}`;h.appendChild(s)}b.appendChild(h);goals[i].forEach((g,j)=>{const e=document.createElement('div');e.className='cell goal';e.style.left=(g.x-2.6)+'%';e.style.top=(g.y-2.6)+'%';e.style.setProperty('--c',COLORS[c].hex);e.textContent='abcd'[j];b.appendChild(e)})});const center=document.createElement('div');center.className='center-mark';center.textContent='Mensch\närgere Dich nicht';b.appendChild(center)}
function pathFor(p,ti){const pos=p.token[ti];if(pos<0)return null;if(pos>=100)return goals[ORDER.indexOf(p.color)][pos-100];return track[pos]}
function canMove(p,ti,n){const pos=p.token[ti];if(pos<0){if(n!==6)return false;const start=starts[ORDER.indexOf(p.color)];return !p.token.some((x,j)=>j!==ti&&x===start);}const next=pos+n;if(next<48)return true;const g=next-48;return g>=0&&g<4&&!p.token.some((x,j)=>j!==ti&&x===100+g)}
function legal(p,n){return p.token.map((_,i)=>canMove(p,i,n)?i:null).filter(i=>i!==null)}
function renderBoard(){document.querySelectorAll('.token').forEach(e=>e.remove());state.players.forEach(p=>p.token.forEach((pos,ti)=>{const t=document.createElement('div');t.className='token';t.style.setProperty('--c',COLORS[p.color].hex);const target=pathFor(p,ti);if(pos<0){const base=document.querySelector(`[data-home="${p.color}-${ti}"]`);if(base){t.style.position='absolute';base.appendChild(t)}}else{t.style.position='absolute';t.style.left=(target.x-2.05)+'%';t.style.top=(target.y-2.05)+'%';if(p.id===state.me?.id&&state.die!==null&&canMove(p,ti,state.die)){t.classList.add('movable');t.addEventListener('click',()=>state.host?move(ti):send(hostConn,{type:'move',id:state.me.id,token:ti}))}$('board').appendChild(t)}}))}
function nextTurn(){state.turn=(state.turn+1)%state.players.length;state.die=null;state.rollAttempts=0}
function roll(){if(!state.host||state.phase!=='playing'||state.die!==null)return;const p=state.players[state.turn];if(!p)return;const n=Math.floor(Math.random()*6)+1;state.die=n;state.rollAttempts++;broadcast();const legalMoves=legal(p,n);if(!legalMoves.length){setTimeout(()=>{if(state.die===n){if(n!==6&&p.token.every(x=>x<0)&&state.rollAttempts<3){state.die=null;broadcast()}else{state.die=null;state.rollAttempts=0;nextTurn();broadcast()}}},900)}}
function move(ti){if(!state.host||state.die===null)return;const p=state.players[state.turn],n=state.die;if(!p||!legal(p,n).includes(ti))return;let next=p.token[ti];if(next<0)next=starts[ORDER.indexOf(p.color)];else next+=n;if(next>=48)next=100+(next-48);if(next<100)state.players.forEach(q=>{if(q.id!==p.id)q.token=q.token.map(x=>x===next?-1:x)});p.token[ti]=next;const won=p.token.every(x=>x>=100);state.die=null;state.rollAttempts=0;if(won)state.phase='finished';else if(n!==6)nextTurn();broadcast()}
function render(){if(state.phase==='lobby'){renderLobby();showGame();$('turnName').textContent='Lobby';$('turnColor').textContent=state.players.length+' Spieler im Raum';$('die').textContent='–';$('rollBtn').disabled=true;$('status').textContent=state.host?(state.players.length<2?'Warte auf weitere Spieler.':'Spiel kann gestartet werden.'):'Warte auf den Gastgeber.';renderBoard();return}$('lobby').classList.add('hidden');$('game').classList.remove('hidden');buildBoard();$('scoreboard').innerHTML=state.players.map((p,i)=>`<div class="player-row ${i===state.turn?'active':''}"><span class="dot" style="background:${COLORS[p.color].hex}"></span><strong>${esc(p.name)}</strong><span>${p.token.filter(x=>x>=100).length}/4</span></div>`).join('');const p=state.players[state.turn];$('turnName').textContent=p?.name||'–';$('turnColor').textContent=p?COLORS[p.color].name:'–';$('turnColor').style.color=p?COLORS[p.color].hex:'';$('die').textContent=state.die??'–';const mine=p?.id===state.me?.id;$('rollBtn').disabled=!mine||state.die!==null||state.phase!=='playing';$('status').textContent=state.phase==='finished'?`${p.name} hat gewonnen.`:mine?(state.die===null?'Du bist dran – würfle.':'Wähle deine blinkende Figur.'):`${p?.name||''} ist am Zug.`;renderBoard()}
$('createBtn').addEventListener('click',create);$('joinBtn').addEventListener('click',join);$('startBtn').addEventListener('click',()=>startGame());$('rollBtn').addEventListener('click',()=>state.host?roll():send(hostConn,{type:'roll',id:state.me.id}));$('newGameBtn').addEventListener('click',()=>location.reload());renderLobby();
